### PR TITLE
MAUT-11515 : Custom object date segment filters should have have same operators than date custom field filters

### PR DESCRIPTION
**Pull request by dadarya0**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | No
| New feature/enhancement? (use the a.x branch)      | Yes
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | Yes 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #https://acquia.atlassian.net/browse/MAUT-11515 

#### Description:
Users noticed that segment filters based on custom object date/datetime fields have different operators than segment filters based on date/datetime custom objects. 

#### Steps to test this PR:

1. Open this PR for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2. Create a custom object with a date and a datetime fields 
3. Create a custom field with a date and a datetime field
4. Create a segment based on above fields and notice the operators.
5. Custom object date/time fields should have the same operators as the normal custom fields.

### CODE REVIEW

**Review by fedys — CHANGES_REQUESTED** [review]
Please fix the failing GH actions.

**Review by fedys — APPROVED** [review]
Thanks @dadarya0! Good job!

**Comment by fedys** [comment]
@rohitp19 you can start your code review.

**Comment by rohitp19** [comment]
@dadarya0 Can you please merge it to beta?

**Comment by dadarya0** [comment]
> @dadarya0 Can you please merge it to beta?

yes, PR is merged and deployed on beta, you can start testing.

**Review by escopecz — APPROVED** [review]
I tested the new operators in https://john.dev.acs.acquia.io/s/segments. All looks good 👍 
Screenshot 2024-07-11 at 09 04 18
Screenshot 2024-07-11 at 09 04 05
Screenshot 2024-07-11 at 09 02 10
Screenshot 2024-07-11 at 09 01 56

**Pull request merged**
