### PR TITLE
Adding GH Actions config

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

#### Steps to test this PR:

1. Open this PR for testing locally (see docs on testing PRs [here](https://contribute.mautic.org/contributing-to-mautic/tester))
2.

### CODE REVIEW

**Comment by escopecz** [comment]
@aadarshjain-dev any idea why is PHPSTAN reporting issues in file
```
 ------ ----------------------------------------------------------------------- 
  Line   DataPersister/CustomItemDataPersister.php                              
 ------ ----------------------------------------------------------------------- 
  9      Class                                                                  
         MauticPlugin\CustomObjectsBundle\DataPersister\CustomItemDataPersiste  
         r implements unknown interface                                         
         ApiPlatform\Core\DataPersister\DataPersisterInterface.                 
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols     
 ------ ----------------------------------------------------------------------- 
```

that doesn't exist in [this branch](https://github.com/acquia/mc-cs-plugin-custom-objects/tree/gh-actions) but [exists in the staging branch](https://github.com/acquia/mc-cs-plugin-custom-objects/blob/staging/DataPersister/CustomItemDataPersister.php)? I don't see how it would be possible with my limited knowledge of Github Action config files.

EDIT: It looks like it's the default behavior and there are good reasons for it: https://github.com/actions/checkout?tab=readme-ov-file#checkout-pull-request-head-commit-instead-of-merge-commit

**Comment by aadarshjain-dev** [comment]
> @aadarshjain-dev any idea why is PHPSTAN reporting issues in file
> 
> ```
>  ------ ----------------------------------------------------------------------- 
>   Line   DataPersister/CustomItemDataPersister.php                              
>  ------ ----------------------------------------------------------------------- 
>   9      Class                                                                  
>          MauticPlugin\CustomObjectsBundle\DataPersister\CustomItemDataPersiste  
>          r implements unknown interface                                         
>          ApiPlatform\Core\DataPersister\DataPersisterInterface.                 
>          💡 Learn more at https://phpstan.org/user-guide/discovering-symbols     
>  ------ ----------------------------------------------------------------------- 
> ```
> 
> that doesn't exist in [this branch](https://github.com/acquia/mc-cs-plugin-custom-objects/tree/gh-actions) but [exists in the staging branch](https://github.com/acquia/mc-cs-plugin-custom-objects/blob/staging/DataPersister/CustomItemDataPersister.php)? I don't see how it would be possible with my limited knowledge of Github Action config files.
> 
> EDIT: It looks like it's the default behavior and there are good reasons for it: https://github.com/actions/checkout?tab=readme-ov-file#checkout-pull-request-head-commit-instead-of-merge-commit

@escopecz so is this particular issue resolved/addressed by you?

**Comment by escopecz** [comment]
Yes, it's resolved. Thanks for asking. I'm trying to make PHPSTAN and PHPUNIT work before we merge this.

**Comment by aadarshjain-dev** [comment]
> Yes, it's resolved. Thanks for asking. I'm trying to make PHPSTAN and PHPUNIT work before we merge this.

Great!!
Also when PHPSTAN and PHPUNIT are fixed, we can remove the commented steps to make the file clean (if not being used further)

**Comment by escopecz** [comment]
Will do!

**Review by fedys — APPROVED** [review]

**Review by rahuld-dev — APPROVED** [review]

**Pull request merged**
