### PR TITLE
Community test fixes

### PR DESCRIPTION
**Pull request by escopecz**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [x]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] Y, current tests are used as they run the changed code
| Related user documentation PR URL      | /
| Related developer documentation PR URL | /
| Issue(s) addressed                     | /

#### Description:

This PR fixes tests when I install the CO plugin to the community Mautic and run them there.

There is slight refactoring because in some cases the table name is needed with and sometimes without the prefix so I added one more method for it and adjusted the usages to use the right one.

#### Steps to test this PR:

As we have no CI at this point, please run PHPUNIT, PHPSTAN and CS Fixer manually.

### CODE REVIEW

**Review by rahuld-dev — APPROVED** [review]
Thank You..! @escopecz

**Review by rohitp19 — APPROVED** [review]
Thanks @escopecz . Looks good.

**Comment by escopecz** [comment]
@himanshu8acquia or @prateek-acq  can you get this merged? I cannot merge it even with 2 approvals. I started a thread to get the CI for this repo prioritized:

https://acquia.slack.com/archives/GUJCLQ936/p1647852411420169

**Comment by prateek-acq** [comment]
> @himanshu8acquia or @prateek-acq can you get this merged? I cannot merge it even with 2 approvals. I started a thread to get the CI for this repo prioritized:
> 
> https://acquia.slack.com/archives/GUJCLQ936/p1647852411420169

Needful has been done.

**Pull request merged**
