### PR TITLE
Adaptation to Mautic v5 - Autowiring + deprecations

### PR DESCRIPTION
**Pull request by volha-pivavarchyk**
| Q                                      | A
| -------------------------------------- | ---
| Bug fix? (use the a.b branch)          | [ ]
| New feature/enhancement? (use the a.x branch)      | [ ]
| Deprecations?                          | [ ]
| BC breaks? (use the c.x branch)        | [ ]
| Automated tests included?              | [ ] 
| Related user documentation PR URL      | mautic/mautic-documentation#... 
| Related developer documentation PR URL | mautic/developer-documentation#... 
| Issue(s) addressed                     | Fixes #... 

:warning: This PR needs the changes from [#308](https://github.com/acquia/mc-cs-plugin-custom-objects/pull/308), [#316](https://github.com/acquia/mc-cs-plugin-custom-objects/pull/316), so they should be put together for testing.

#### Description:

This PR adds autowiring and fixes some deprecations.

#### Steps to test this PR:

1. Setup a custom object. Use Mautic v5.
2. Make sure everything is working.

### CODE REVIEW

**Comment by adiux** [comment]
who would be able to review this?

**Comment by escopecz** [comment]
This is only one part of the changes required for M5. Other big refactoring will have to happen for migrating PHP templates to Twig. But it's a good start.

We should not merge this to the `staging` branch though. I'll create a `5.x` branch where we can work on M5 changes without breaking the plugin for M4. Sounds good?

**Comment by jaetoole** [comment]
@volha-pivavarchyk this PR seems to give me the following error:
image

**Comment by byt3sage** [comment]
@escopecz - this PR is dependent on 2-3 other PRs which makes it a bit of a nightmare to test.

Can we merge these v5 PRs into an intemediary branch (maybe 5.x-test if you don't want to straight push them into 5.x)? I'm happy to give these a really good test with my team but need it to be simple enough for us to be able to do :)

**Comment by volha-pivavarchyk** [comment]
@jaetoole There are some PRs which should be merged. I can put them together and create a new PR to make test easier. But I can do it only at the weekend.

**Comment by byt3sage** [comment]
> @jaetoole There are some PRs which should be merged. I can put them together and create a new PR to make test easier. But I can do it only at the weekend.

That would be great! Unless @escopecz gets to it first :)

**Comment by volha-pivavarchyk** [comment]
Closing in favor #338

**Pull request closed without merging**
